
data:
  dataset: osrt
  num_points: 2304
model:
  encoder: osrt
  encoder_kwargs:
    pos_start_octave: -5
    num_slots: 32
  decoder: slot_mixer
  decoder_kwargs:
    pos_start_octave: -5

training:
  num_workers: 1
  batch_size: 256
  model_selection_metric: psnr
  model_selection_mode: maximize
  print_every: 10
  visualize_every: 2000
  validate_every: 2000
  checkpoint_every: 200
  backup_every: 25000
  max_it: 4000000
  decay_it: 4000000
  lr_warmup: 10000

